name: Create new release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Get the tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Build
        run: |
          npm install
          composer install
          composer release
          mkdir scoby-analytics && cd scoby-analytics && unzip ../scoby-analytics.zip && cd .. \
            && rm scoby-analytics.zip && zip -r scoby-analytics.zip scoby-analytics
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "scoby-analytics.zip"
          tag: ${{ steps.get_version.outputs.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
